services:
  dev:
    container_name: dev
    build: # use the Dockerfile in the current directory
      context: .
      dockerfile: Dockerfile
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2222:22" # SSH
      - "7777:7777" # GDB Server
#  dev2:
#    container_name: dev2
#    build: # use the Dockerfile in the current directory
#      context: .
#      dockerfile: Dockerfile
#    security_opt: # options needed for gdb debugging
#      - seccomp:unconfined
#      - apparmor:unconfined
#    ports:
#      - "2222:22" # SSH
#      - "7777:7777" # GDB Server
#    volumes:
#      -